# A list of devices you want to take the screenshots from
devices([
  "iPhone 15 Pro Max",
  "iPhone 15 Pro",
  "iPhone SE (3rd generation)",
  "iPad Pro (12.9-inch) (6th generation)"
])

languages([
  "ja-JP",
  "en-US"
])

# The name of the scheme which contains the UI Tests
scheme("Runner")

# Where should the resulting screenshots be stored?
output_directory("./screenshots")

# Clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Arguments to pass to the app on launch
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot